# Site settings
title: jekyll-highlight-rgbasm
description: >-
  A Jekyll plugin using Rouge to highlight RGBASM Game Boy assembly language.
baseurl: "/jekyll-highlight-rgbasm"
url: "https://martendo.github.io/jekyll-highlight-rgbasm"

# Build settings
theme: null
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

exclude:
  - README.md
  - LICENSE

# Pygments styles
styles:
  - default
  - abap
  - algol
  - algol_nu
  - arduino
  - autumn
  - borland
  - bw
  - colorful
  - emacs
  - friendly
  - fruity
  - gruvbox-dark
  - gruvbox-light
  - igor
  - inkpot
  - lovelace
  - manni
  - material
  - monokai
  - murphy
  - native
  - paraiso-dark
  - paraiso-light
  - pastie
  - perldoc
  - rainbow_dash
  - rrt
  - sas
  - solarized-dark
  - solarized-light
  - stata-dark
  - stata-light
  - tango
  - trac
  - vim
  - vs
  - xcode
  - zenburn
