name: Build GitHub Pages

on:
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Build GitHub Pages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.4
          bundler-cache: true

      - name: Build site
        run: bundle exec jekyll build

      - name: Organize
        run: |
          GLOBIGNORE="_site:.git"
          rm -rf *
          unset GLOBIGNORE
          mv -t . _site/*
          rmdir _site

      - name: Deploy
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git checkout --orphan gh-pages
          git reset
          git add .
          git commit --message="Build GitHub Pages"
          git push --force origin gh-pages
