name: Build GitHub Pages

on:
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Build site
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.4
          bundler-cache: true

      - name: Build site
        run: bundle exec jekyll build

      - name: Organize
        run: |
          shopt -s dotglob
          GLOBIGNORE="_site"
          rm -rf *
          unset GLOBIGNORE
          shopt -u dotglob
          mv -t . _site/*
          rmdir _site

      - name: Store build
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: .

  deploy:
    name: Deploy to GitHub Pages
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: gh-pages

      - name: Empty working directory
        run: rm -rf *

      - name: Get build
        uses: actions/download-artifact@v2
        with:
          name: build

      - name: Deploy
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git add --all
          git commit --message="Update build"
          git push origin gh-pages
